grant insert on equip_owner.audit_entry to update_any_equip_owner;
grant insert, update, delete on equip_owner.lock_control to update_any_equip_owner;
grant insert, update, delete on equip_owner.event_type to update_any_equip_owner;
grant insert, update, delete on equip_owner.event to update_any_equip_owner;
grant insert, update, delete on equip_owner.notification_type to update_any_equip_owner;
grant insert, update, delete on equip_owner.subscription to update_any_equip_owner;
grant insert, update, delete on equip_owner.notification to update_any_equip_owner;
grant insert, update, delete on equip_owner.operational_metadata_job to update_any_equip_owner;
grant insert, update, delete on equip_owner.report_job to update_any_equip_owner;
grant insert, update, delete on equip_owner.report_job_output to update_any_equip_owner;
grant insert, update, delete on equip_owner.security_group to update_any_equip_owner;
grant insert, update, delete on equip_owner.security_group_access to update_any_equip_owner;
grant insert, update, delete on equip_owner.security_role to update_any_equip_owner;
grant insert, update, delete on equip_owner.security_priv to update_any_equip_owner;
grant insert, update, delete on equip_owner.security_role_priv to update_any_equip_owner;
grant insert, update, delete on equip_owner.security_role_event_type to update_any_equip_owner;
grant insert, update, delete on equip_owner.list_value to update_any_equip_owner;
grant insert, update, delete on equip_owner.list_name to update_any_equip_owner;
grant insert, update, delete on equip_owner.list to update_any_equip_owner;

grant select on equip_owner.legacy_entity_status to select_any_equip_owner;
grant select on equip_owner.audit_entry to select_any_equip_owner;
grant select on equip_owner.lock_control to select_any_equip_owner;
grant select on equip_owner.event_type to select_any_equip_owner;
grant select on equip_owner.event to select_any_equip_owner;
grant select on equip_owner.notification_type to select_any_equip_owner;
grant select on equip_owner.subscription to select_any_equip_owner;
grant select on equip_owner.notification to select_any_equip_owner;
grant select on equip_owner.operational_metadata_job to select_any_equip_owner;
grant select on equip_owner.report_job to select_any_equip_owner;
grant select on equip_owner.report_job_output to select_any_equip_owner;
grant select on equip_owner.security_group to select_any_equip_owner;
grant select on equip_owner.security_group_access to select_any_equip_owner;
grant select on equip_owner.security_role to select_any_equip_owner;
grant select on equip_owner.security_priv to select_any_equip_owner;
grant select on equip_owner.security_role_priv to select_any_equip_owner;
grant select on equip_owner.security_role_event_type to select_any_equip_owner;
grant select on equip_owner.list_value to select_any_equip_owner;
grant select on equip_owner.list_name to select_any_equip_owner;
grant select on equip_owner.list to select_any_equip_owner;
